@echo off
REM ****************************************************************************
REM Vivado (TM) v2022.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Mon Oct 28 14:27:26 -0500 2024
REM SW Build 3671981 on Fri Oct 14 05:00:03 MDT 2022
REM
REM IP Build 3669848 on Fri Oct 14 08:30:02 MDT 2022
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim edge_detector_tb_behav -key {Behavioral:sim_1:Functional:edge_detector_tb} -tclbatch edge_detector_tb.tcl -protoinst "protoinst_files/design_1.protoinst" -log simulate.log"
call xsim  edge_detector_tb_behav -key {Behavioral:sim_1:Functional:edge_detector_tb} -tclbatch edge_detector_tb.tcl -protoinst "protoinst_files/design_1.protoinst" -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
